version: 2.1

jobs:
  build_release:
    parameters:
        do_release:
          type: boolean

    docker:
    - image: circleci/ruby:2.5-node

    steps:
      - checkout
      - setup_remote_docker

      - run: ./scripts/install-gems
      - run: docker info
      - run: rake build

      - when:
          condition: << parameters.do_release >>
          steps:
            - run:
                name: Push Docker image
                command: |
                  docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
                  rake deploy


workflows:
  workflow:
    jobs:
      - build_release:
          do_release: false
          filters:
            branches:
              ignore: master
      - build_release:
          do_release: true
          filters:
            branches:
              only: master
