on:
  push:
    branches:
      - main
      - ci
jobs:
  build:
    env:
      GLOBAL_GEMS: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          cache-version: 2

      - name: Build site
        run: bundle exec jekyll build --config _config.yml

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        if: github.ref == 'refs/heads/main'
