on:
  push:
    branches:
      - main
  schedule:
    - cron: 1 0 * * *
  pull_request: {}
name: Build & Publish
jobs:
  build:
    env:
      GLOBAL_GEMS: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 2

      - name: Build & Validate
        run: rake validate

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        if: github.ref == 'refs/heads/main'
