name: Build & Publish

on:
  push:
    branches:
      - main
  schedule:
    # This is here to ensure that the calendar shows the correct next event
    - cron: 1 0 * * *
  pull_request: {}

jobs:
  build:
    env:
      # ruby/setup-ruby@v1 does not offer a way to change the cached gems path.
      # See https://github.com/ruby/setup-ruby/issues/291
      GLOBAL_GEMS: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          cache-version: 2

      - name: Build & Validate
        run: rake validate

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        if: github.ref == 'refs/heads/main'
